{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2019-4568",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/exchange.xforce.ibmcloud.com\/vulnerabilities\/166629",
                    "name": "ibm-mq-cve20194568-dos (166629)",
                    "refsource": "XF",
                    "tags": []
                },
                {
                    "url": "https:\/\/www.ibm.com\/support\/pages\/node\/1106517",
                    "name": "https:\/\/www.ibm.com\/support\/pages\/node\/1106517",
                    "refsource": "CONFIRM",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "IBM MQ and IBM MQ Appliance 8.0 and 9.0 LTS could allow a remote attacker with intimate knowledge of the server to cause a denial of service when receiving data on the channel. IBM X-Force ID: 166629."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2020-01-28T19:15Z",
    "lastModifiedDate": "2020-01-28T19:39Z"
}