{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2019-4655",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/exchange.xforce.ibmcloud.com\/vulnerabilities\/170966",
                    "name": "ibm-mq-cve20194655-dos (170966)",
                    "refsource": "XF",
                    "tags": []
                },
                {
                    "url": "https:\/\/www.ibm.com\/support\/pages\/node\/1106529",
                    "name": "https:\/\/www.ibm.com\/support\/pages\/node\/1106529",
                    "refsource": "CONFIRM",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "IBM MQ 9.1.0.0, 9.1.0.1, 9.1.0.2, 9.1.0.3, 9.1.1, 9.1.2, and 9.1.3 is vulnerable to a denial of service attack that would allow an authenticated user to reset client connections due to an error within the Data Conversion routine. IBM X-Force ID: 170966."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2019-12-30T16:15Z",
    "lastModifiedDate": "2019-12-30T17:00Z"
}