{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2019-19331",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=CVE-2019-19331",
                    "name": "https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=CVE-2019-19331",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https:\/\/www.knot-resolver.cz\/2019-12-04-knot-resolver-4.3.0.html",
                    "name": "https:\/\/www.knot-resolver.cz\/2019-12-04-knot-resolver-4.3.0.html",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "knot-resolver before version 4.3.0 is vulnerable to denial of service through high CPU utilization. DNS replies with very many resource records might be processed very inefficiently, in extreme cases taking even several CPU seconds for each such uncached message. For example, a few thousand A records can be squashed into one DNS message (limit is 64kB)."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2019-12-16T16:15Z",
    "lastModifiedDate": "2019-12-16T16:59Z"
}