{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2019-19221",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/github.com\/libarchive\/libarchive\/commit\/22b1db9d46654afc6f0c28f90af8cdc84a199f41",
                    "name": "https:\/\/github.com\/libarchive\/libarchive\/commit\/22b1db9d46654afc6f0c28f90af8cdc84a199f41",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/libarchive\/libarchive\/issues\/1276",
                    "name": "https:\/\/github.com\/libarchive\/libarchive\/issues\/1276",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "In Libarchive 3.4.0, archive_wstring_append_from_mbs in archive_string.c has an out-of-bounds read because of an incorrect mbrtowc or mbtowc call. For example, bsdtar crashes via a crafted archive."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2019-11-21T23:15Z",
    "lastModifiedDate": "2019-11-22T13:17Z"
}