{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2019-19344",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "http:\/\/lists.opensuse.org\/opensuse-security-announce\/2020-01\/msg00055.html",
                    "name": "openSUSE-SU-2020:0122",
                    "refsource": "SUSE",
                    "tags": []
                },
                {
                    "url": "https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=CVE-2019-19344",
                    "name": "https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=CVE-2019-19344",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https:\/\/security.netapp.com\/advisory\/ntap-20200122-0001\/",
                    "name": "https:\/\/security.netapp.com\/advisory\/ntap-20200122-0001\/",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https:\/\/usn.ubuntu.com\/4244-1\/",
                    "name": "USN-4244-1",
                    "refsource": "UBUNTU",
                    "tags": []
                },
                {
                    "url": "https:\/\/www.samba.org\/samba\/security\/CVE-2019-19344.html",
                    "name": "https:\/\/www.samba.org\/samba\/security\/CVE-2019-19344.html",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https:\/\/www.synology.com\/security\/advisory\/Synology_SA_20_01",
                    "name": "https:\/\/www.synology.com\/security\/advisory\/Synology_SA_20_01",
                    "refsource": "CONFIRM",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "There is a use-after-free issue in all samba 4.9.x versions before 4.9.18, all samba 4.10.x versions before 4.10.12 and all samba 4.11.x versions before 4.11.5, essentially due to a call to realloc() while other local variables still point at the original buffer."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2020-01-21T18:15Z",
    "lastModifiedDate": "2020-01-21T18:56Z"
}