{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-5278",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/github.com\/PrestaShop\/PrestaShop\/commit\/ea85210d6e5d81f058b55764bc4608cdb0b36c5d",
                    "name": "https:\/\/github.com\/PrestaShop\/PrestaShop\/commit\/ea85210d6e5d81f058b55764bc4608cdb0b36c5d",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/PrestaShop\/PrestaShop\/security\/advisories\/GHSA-mrpj-67mq-3fr5",
                    "name": "https:\/\/github.com\/PrestaShop\/PrestaShop\/security\/advisories\/GHSA-mrpj-67mq-3fr5",
                    "refsource": "CONFIRM",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "In PrestaShop between versions 1.5.4.0 and 1.7.6.5, there is a reflected XSS on Exception page The problem is fixed in 1.7.6.5"
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2020-04-20T17:15Z",
    "lastModifiedDate": "2020-04-20T17:21Z"
}