{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-3913",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/support.apple.com\/HT211100",
                    "name": "https:\/\/support.apple.com\/HT211100",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https:\/\/support.apple.com\/HT211102",
                    "name": "https:\/\/support.apple.com\/HT211102",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https:\/\/support.apple.com\/HT211103",
                    "name": "https:\/\/support.apple.com\/HT211103",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "A permissions issue existed. This issue was addressed with improved permission validation. This issue is fixed in iOS 13.4 and iPadOS 13.4, macOS Catalina 10.15.4, watchOS 6.2. A malicious application may be able to elevate privileges."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2020-04-01T18:15Z",
    "lastModifiedDate": "2020-04-01T18:25Z"
}