{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-5277",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/github.com\/PrestaShop\/ps_facetedsearch\/commit\/c792ddcdd84ec208a6dfa4a30fd66d8bc9863f4a",
                    "name": "https:\/\/github.com\/PrestaShop\/ps_facetedsearch\/commit\/c792ddcdd84ec208a6dfa4a30fd66d8bc9863f4a",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/PrestaShop\/ps_facetedsearch\/security\/advisories\/GHSA-mmmv-m5q9-g3cm",
                    "name": "https:\/\/github.com\/PrestaShop\/ps_facetedsearch\/security\/advisories\/GHSA-mmmv-m5q9-g3cm",
                    "refsource": "CONFIRM",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "PrestaShop module ps_facetedsearch versions before 3.5.0 has a reflected XSS with `url_name` parameter. The problem is fixed in 3.5.0"
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2020-03-25T19:15Z",
    "lastModifiedDate": "2020-03-25T19:15Z"
}