{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-7041",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/github.com\/adrienverge\/openfortivpn\/commit\/cd9368c6a1b4ef91d77bb3fdbe2e5bc34aa6f4c4",
                    "name": "https:\/\/github.com\/adrienverge\/openfortivpn\/commit\/cd9368c6a1b4ef91d77bb3fdbe2e5bc34aa6f4c4",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/adrienverge\/openfortivpn\/issues\/536",
                    "name": "https:\/\/github.com\/adrienverge\/openfortivpn\/issues\/536",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "An issue was discovered in openfortivpn 1.11.0 when used with OpenSSL 1.0.2 or later. tunnel.c mishandles certificate validation because an X509_check_host negative error code is interpreted as a successful return value."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2020-02-27T18:15Z",
    "lastModifiedDate": "2020-02-27T18:45Z"
}