{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-8632",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/bugs.launchpad.net\/ubuntu\/+source\/cloud-init\/+bug\/1860795",
                    "name": "https:\/\/bugs.launchpad.net\/ubuntu\/+source\/cloud-init\/+bug\/1860795",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/canonical\/cloud-init\/pull\/189",
                    "name": "https:\/\/github.com\/canonical\/cloud-init\/pull\/189",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "In cloud-init through 19.4, rand_user_password in cloudinit\/config\/cc_set_passwords.py has a small default pwlen value, which makes it easier for attackers to guess passwords."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2020-02-05T14:15Z",
    "lastModifiedDate": "2020-02-05T14:45Z"
}